"""
cogs/security/spam_trap.py
=============================
Spam Trap (SPEC.md §7.3): un canale trappola dove scrivere significa
ban istantaneo. Modulo CANDIDATO PREMIUM.

Sequenza fissa (vedi PROGRESS.md § Decisioni prese — NON riordinare):
  1. Cattura contenuto del messaggio che ha scatenato la trappola
  2. Raccolta dati per il transcript (PRIMA di qualunque cancellazione)
  3. DM all'utente — PRIMA del ban (dopo, niente server in comune)
  4. Ban con delete_message_seconds (max 7 giorni nativi Discord)
  5. Creazione del case (riusa moderation_cases, action_type
     "spam_trap_ban" — non un proprio sistema di case duplicato)
  6. Purge supplementare (finestra 7-30 giorni, oltre quanto già
     coperto dal ban nativo)
  7. Cleanup webhook/inviti creati dall'utente (via audit log)
  8. Log completo in #spam-log

Nota sul contenuto dei messaggi: NON richiede il Message Content
Intent. Vedi la spiegazione completa in core/spam_trap_logic.py —
il contenuto viene sempre recuperato via fetch REST esplicito
(channel.fetch_message), mai letto dall'evento gateway in tempo
reale. Assunzione sul comportamento reale dell'API Discord, da
verificare sul server di test.

Scope scelto per l'appeal — view NON persistente: a differenza dei
pannelli ticket/vocali (che restano pubblicati per mesi), una
conversazione di appeal è per natura di breve durata. La view ha un
timeout di 7 giorni; se il bot si riavvia nel mezzo di un appeal
aperto, i bottoni di quella specifica conversazione smettono di
rispondere (l'utente può comunque riscrivere in DM per riaprirla,
soggetto al cooldown di 24h). Scelta dichiarata, non un errore.
"""

from __future__ import annotations

import asyncio
import io
import logging
from collections import defaultdict
from datetime import datetime, timezone

import discord
from discord import app_commands
from discord.ext import commands

from core.database import db
from core.image_thumbnail import generate_thumbnail
from core.image_thumbnail_logic import (
    bytes_to_data_uri,
    is_image_attachment,
    is_within_size_limit,
)
from core.invite_tracker import invite_tracker
from core.premium import PremiumModule, registry
from core.repositories.moderation_repo import moderation_repo
from core.repositories.spam_trap_repo import spam_trap_repo
from core.spam_trap_logic import (
    can_appeal,
    partition_messages_for_deletion,
    purge_window,
)
from core.spam_trap_transcript import TranscriptEntry, build_transcript_html

logger = logging.getLogger("iyokai.spam_trap")

MODULE_SPAM_TRAP = "spam_trap"

TRAP_CHANNEL_DEFAULT_NAME = "spam-trap"
LOG_CHANNEL_DEFAULT_NAME = "spam-log"

BAN_ACTION_TYPE = "spam_trap_ban"

# Copy in inglese per gli embed dei canali — richiesto esplicitamente
# dalla specifica originale ("il tutto ovviamente rigorosamente in
# inglese").
TRAP_EMBED_DESCRIPTION = (
    "# DO NOT WRITE IN THIS CHANNEL — YOU WILL BE BANNED\n\n"
    "This channel is part of the automated security system of this server. "
    "Any message sent here results in an immediate and permanent ban. "
    "It exists to detect and stop raids, spam and scam campaigns.\n\n"
    "This is an automated message. Please use the regular channels of the "
    "server to talk with the community."
)

LOG_EMBED_DESCRIPTION = (
    "**Security Log Channel**\n\n"
    "This channel collects the reports generated by the spam trap system. "
    "For every triggered ban you will find here: user tag and ID, join date, "
    "ban date, invite code used and its creator, the content that triggered "
    "the trap, and the number of deleted messages."
)


def _ban_dm_description(guild_name: str) -> str:
    return (
        f"You have been banned from **{guild_name}** for using a restricted "
        f"security channel.\n\n"
        f"If you believe this was a mistake (for example, you posted in the "
        f"wrong channel by accident), reply to this message to appeal. "
        f"Staff will review your case within a reasonable time.\n\n"
        f"You can only submit one appeal every 24 hours."
    )


class AppealActionsView(discord.ui.View):
    """
    Bottoni per la gestione dell'appeal, mostrati nel thread privato
    in #spam-log. NON persistente — vedi la nota in cima al file per
    il motivo della scelta.
    """

    def __init__(self, guild_id: int, case_number: int, user_id: int) -> None:
        super().__init__(timeout=7 * 24 * 3600)
        self.guild_id = guild_id
        self.case_number = case_number
        self.user_id = user_id

    async def _disable_and_update(
        self, interaction: discord.Interaction, content: str
    ) -> None:
        for child in self.children:
            child.disabled = True
        self.stop()
        await interaction.response.edit_message(content=content, view=self)

    @discord.ui.button(label="Unban", style=discord.ButtonStyle.success)
    async def unban(
        self, interaction: discord.Interaction, button: discord.ui.Button
    ) -> None:
        guild = interaction.client.get_guild(self.guild_id)
        if guild is None:
            await interaction.response.send_message(
                "I'm no longer in that server.", ephemeral=True
            )
            return

        try:
            await guild.unban(
                discord.Object(id=self.user_id),
                reason=f"Spam trap appeal approved by {interaction.user}",
            )
        except discord.NotFound:
            pass  # già sbannato, procediamo comunque
        except discord.Forbidden:
            await interaction.response.send_message(
                "Missing permissions to unban.", ephemeral=True
            )
            return

        await moderation_repo.revoke_case(
            self.guild_id, self.case_number, interaction.user.id
        )

        try:
            user = await interaction.client.fetch_user(self.user_id)
            await user.send(
                f"Your ban appeal for **{guild.name}** was approved. "
                f"You can rejoin the server."
            )
        except discord.HTTPException:
            pass

        await self._disable_and_update(interaction, "✅ Unbanned — appeal approved.")

    @discord.ui.button(label="Reject", style=discord.ButtonStyle.danger)
    async def reject(
        self, interaction: discord.Interaction, button: discord.ui.Button
    ) -> None:
        guild = interaction.client.get_guild(self.guild_id)
        try:
            user = await interaction.client.fetch_user(self.user_id)
            guild_name = guild.name if guild else "the server"
            await user.send(
                f"Your ban appeal for **{guild_name}** was reviewed and denied."
            )
        except discord.HTTPException:
            pass

        await self._disable_and_update(interaction, "❌ Appeal rejected.")

    @discord.ui.button(label="Reply", style=discord.ButtonStyle.secondary)
    async def reply(
        self, interaction: discord.Interaction, button: discord.ui.Button
    ) -> None:
        await interaction.response.send_modal(StaffReplyModal(self.user_id))


class StaffReplyModal(discord.ui.Modal, title="Reply to user"):
    # discord.ui.Label che avvolge il TextInput è il pattern corretto
    # e non deprecato (TextInput.label= è deprecato a favore di
    # questo — verificato con discord.py 2.7.1 prima di scrivere
    # questo file: TextInput.label produce un DeprecationWarning
    # reale, non solo teorico). Il valore digitato si legge da
    # message_label.component.value in on_submit, non da un
    # attributo TextInput separato.
    message_label = discord.ui.Label(
        text="Your message",
        component=discord.ui.TextInput(style=discord.TextStyle.paragraph, max_length=1500),
    )

    def __init__(self, user_id: int) -> None:
        super().__init__()
        self.user_id = user_id

    async def on_submit(self, interaction: discord.Interaction) -> None:
        try:
            user = await interaction.client.fetch_user(self.user_id)
            await user.send(f"**Staff reply:** {self.message_label.component.value}")
            await interaction.response.send_message("Message sent.", ephemeral=True)
        except discord.HTTPException:
            await interaction.response.send_message(
                "Couldn't deliver the message (DMs closed).", ephemeral=True
            )


class SpamTrapCog(commands.Cog):
    def __init__(self, bot: commands.Bot) -> None:
        self.bot = bot

    # ================================================================
    # Setup
    # ================================================================
    @app_commands.command(
        name="spamtrap-setup",
        description="[Admin] Configura i canali trappola e log dello Spam Trap.",
    )
    @app_commands.describe(
        trap_channel="Canale trappola (se non scelto, ne viene creato uno)",
        log_channel="Canale dei log (se non scelto, ne viene creato uno)",
    )
    @app_commands.checks.has_permissions(manage_guild=True)
    async def spamtrap_setup(
        self,
        interaction: discord.Interaction,
        trap_channel: discord.TextChannel | None = None,
        log_channel: discord.TextChannel | None = None,
    ) -> None:
        guild = interaction.guild
        if guild is None:
            await interaction.response.send_message(
                "Questo comando è disponibile solo dentro un server.",
                ephemeral=True,
            )
            return

        await interaction.response.defer(ephemeral=True)

        created_trap = trap_channel is None
        created_log = log_channel is None

        if trap_channel is None:
            trap_channel = await self._create_trap_channel(guild)
        if log_channel is None:
            log_channel = await self._create_log_channel(guild)

        await spam_trap_repo.set_config(guild.id, trap_channel.id, log_channel.id)

        if created_trap:
            await self._send_trap_embed(trap_channel)
        if created_log:
            await self._send_log_embed(log_channel)

        await interaction.followup.send(
            f"Spam Trap configurato: trappola in {trap_channel.mention}, "
            f"log in {log_channel.mention}.",
            ephemeral=True,
        )

    async def _create_trap_channel(self, guild: discord.Guild) -> discord.TextChannel:
        overwrites = {
            guild.default_role: discord.PermissionOverwrite(
                create_instant_invite=False,
                manage_webhooks=False,
            )
        }
        return await guild.create_text_channel(
            TRAP_CHANNEL_DEFAULT_NAME,
            overwrites=overwrites,
            reason="iYokai Spam Trap setup",
        )

    async def _create_log_channel(self, guild: discord.Guild) -> discord.TextChannel:
        overwrites = {
            guild.default_role: discord.PermissionOverwrite(view_channel=False)
        }
        return await guild.create_text_channel(
            LOG_CHANNEL_DEFAULT_NAME,
            overwrites=overwrites,
            reason="iYokai Spam Trap setup",
        )

    async def _send_trap_embed(self, channel: discord.TextChannel) -> None:
        embed = discord.Embed(
            description=TRAP_EMBED_DESCRIPTION,
            color=discord.Color.from_rgb(255, 45, 0),
        )
        await channel.send(embed=embed)

    async def _send_log_embed(self, channel: discord.TextChannel) -> None:
        embed = discord.Embed(
            description=LOG_EMBED_DESCRIPTION,
            color=discord.Color.from_rgb(59, 165, 93),
        )
        await channel.send(embed=embed)

    # ================================================================
    # Indicizzazione + trigger
    # ================================================================
    @commands.Cog.listener()
    async def on_message(self, message: discord.Message) -> None:
        if message.author.bot:
            return

        if message.guild is None:
            await self._handle_possible_appeal(message)
            return

        if not await db.is_module_active_for_guild(message.guild.id, MODULE_SPAM_TRAP):
            return

        if isinstance(message.channel, discord.TextChannel):
            await spam_trap_repo.index_message(
                message.id,
                message.guild.id,
                message.channel.id,
                message.author.id,
                message.created_at,
            )

        config = await spam_trap_repo.get_config(message.guild.id)
        if config.trap_channel_id is not None and message.channel.id == config.trap_channel_id:
            await self._handle_trigger(message)

    @commands.Cog.listener()
    async def on_member_join(self, member: discord.Member) -> None:
        if not await db.is_module_active_for_guild(member.guild.id, MODULE_SPAM_TRAP):
            return
        risultato = await invite_tracker.find_used_invite(member.guild)
        code, creator_id = risultato if risultato else (None, None)
        await spam_trap_repo.record_join_invite(member.guild.id, member.id, code, creator_id)

    # ================================================================
    # Sequenza di ban
    # ================================================================
    async def _handle_trigger(self, message: discord.Message) -> None:
        guild = message.guild
        user = message.author
        now = datetime.now(timezone.utc)

        # 1. Contenuto del messaggio trigger — via fetch REST (vedi
        #    nota architetturale in cima al file).
        trigger_content = ""
        try:
            fetched = await message.channel.fetch_message(message.id)
            trigger_content = fetched.content or ""
        except (discord.NotFound, discord.Forbidden, discord.HTTPException):
            logger.warning(
                "Impossibile recuperare il contenuto del messaggio trigger "
                "(id=%s) nel server %s.",
                message.id,
                guild.id,
            )

        # 2. Transcript — PRIMA di qualunque cancellazione.
        transcript_entries = await self._gather_transcript_entries(guild, user)
        avatar_data_uri = await self._build_author_avatar(user)
        transcript_html = build_transcript_html(
            transcript_entries,
            title=f"Spam Trap — {user} — {guild.name}",
            generated_at=now,
            author_avatar_data_uri=avatar_data_uri,
        )

        # 3. DM PRIMA del ban.
        dm_sent = await self._send_ban_dm(guild, user)

        # 4. Ban.
        try:
            await guild.ban(
                user,
                reason="Spam trap triggered",
                delete_message_seconds=7 * 86400,
            )
        except discord.Forbidden:
            logger.error(
                "Permessi insufficienti per bannare %s nel server %s "
                "(Spam Trap).",
                user.id,
                guild.id,
            )
            return
        except discord.HTTPException:
            logger.exception("Errore HTTP bannando %s (Spam Trap).", user.id)
            return

        # 5. Case (riusa il case system di Moderation).
        case_number = await moderation_repo.create_case(
            guild_id=guild.id,
            user_id=user.id,
            moderator_id=self.bot.user.id,
            action_type=BAN_ACTION_TYPE,
            reason="Triggered the spam trap channel",
        )

        # 6. Purge supplementare (7-30 giorni).
        deleted_by_channel = await self._purge_supplementary(guild, user, now)

        # 7. Cleanup webhook/inviti.
        await self._cleanup_user_artifacts(guild, user)

        # 8. Invito usato al join.
        join_invite = await spam_trap_repo.get_latest_join_invite(guild.id, user.id)
        invite_code, invite_creator_id = join_invite if join_invite else (None, None)

        # 9. Incidente (contesto + transcript).
        await spam_trap_repo.create_incident(
            guild.id,
            case_number,
            trigger_content,
            invite_code,
            invite_creator_id,
            deleted_by_channel,
            transcript_html,
        )

        # 10. Log.
        await self._send_ban_log(
            guild, user, case_number, trigger_content,
            invite_code, invite_creator_id, deleted_by_channel, dm_sent,
        )

    async def _send_ban_dm(self, guild: discord.Guild, user: discord.abc.User) -> bool:
        embed = discord.Embed(
            title="You have been banned",
            description=_ban_dm_description(guild.name),
            color=discord.Color.red(),
        )
        try:
            await user.send(embed=embed)
            return True
        except (discord.Forbidden, discord.HTTPException):
            return False

    async def _build_author_avatar(self, user: discord.abc.User) -> str | None:
        """
        Scarica l'avatar dell'utente bannato UNA SOLA VOLTA per
        l'intero report (non per ogni messaggio — vedi la nota in
        core/spam_trap_transcript.py sul perché ha senso farlo così).
        Restituisce None se il download o l'elaborazione falliscono:
        il transcript deve generarsi comunque, senza avatar, non
        fallire per questo dettaglio accessorio.
        """
        try:
            avatar_bytes = await user.display_avatar.read()
        except discord.HTTPException:
            return None

        thumbnail_bytes = await asyncio.to_thread(generate_thumbnail, avatar_bytes)
        if thumbnail_bytes is None:
            return None
        return bytes_to_data_uri(thumbnail_bytes)

    async def _build_thumbnails(self, attachments: list[discord.Attachment]) -> list[str]:
        """
        Scarica e rigenera come thumbnail ogni allegato immagine,
        restituendo le data URI pronte per il transcript. Pillow è
        sincrono/CPU-bound: l'elaborazione vera gira in un thread
        separato (asyncio.to_thread) per non bloccare l'event loop
        del bot mentre elabora un'immagine — bloccarlo anche solo per
        una frazione di secondo può causare timeout dell'heartbeat
        verso Discord su un bot con molti server attivi insieme.
        """
        data_uris: list[str] = []
        for attachment in attachments:
            if not is_image_attachment(attachment.filename, attachment.content_type):
                continue
            if not is_within_size_limit(attachment.size):
                logger.info(
                    "Allegato immagine troppo grande (%d byte) per la "
                    "thumbnail, saltato: %s",
                    attachment.size,
                    attachment.filename,
                )
                continue
            try:
                image_bytes = await attachment.read()
            except discord.HTTPException:
                continue

            thumbnail_bytes = await asyncio.to_thread(generate_thumbnail, image_bytes)
            if thumbnail_bytes is not None:
                data_uris.append(bytes_to_data_uri(thumbnail_bytes))
        return data_uris

    async def _gather_transcript_entries(
        self, guild: discord.Guild, user: discord.abc.User
    ) -> list[TranscriptEntry]:
        indexed = await spam_trap_repo.get_all_user_messages(guild.id, user.id)
        entries: list[TranscriptEntry] = []

        for record in indexed:
            channel = guild.get_channel(record.channel_id)
            if channel is None:
                continue
            try:
                fetched = await channel.fetch_message(record.message_id)
                thumbnails = await self._build_thumbnails(fetched.attachments)
                entries.append(
                    TranscriptEntry(
                        timestamp=record.created_at,
                        author_display_name=fetched.author.display_name,
                        author_tag=str(fetched.author),
                        content=fetched.content or "",
                        attachment_filenames=[a.filename for a in fetched.attachments],
                        attachment_thumbnail_data_uris=thumbnails,
                        is_deleted_source=False,
                    )
                )
            except (discord.NotFound, discord.Forbidden, discord.HTTPException):
                # Il messaggio non è più recuperabile: lo segnaliamo
                # comunque nel transcript (posizione temporale nota
                # dall'indice), ma senza contenuto.
                entries.append(
                    TranscriptEntry(
                        timestamp=record.created_at,
                        author_display_name=str(user),
                        author_tag=str(user),
                        content="",
                        attachment_filenames=[],
                        is_deleted_source=True,
                    )
                )

        return entries

    async def _purge_supplementary(
        self, guild: discord.Guild, user: discord.abc.User, now: datetime
    ) -> dict[str, int]:
        start, end = purge_window(now)
        indexed = await spam_trap_repo.get_user_messages_in_window(
            guild.id, user.id, start, end
        )
        records = [(m.message_id, m.created_at) for m in indexed]
        bulk_ids, individual_ids = partition_messages_for_deletion(records, now)

        by_channel_bulk: dict[int, list[int]] = defaultdict(list)
        message_channel = {m.message_id: m.channel_id for m in indexed}
        for mid in bulk_ids:
            by_channel_bulk[message_channel[mid]].append(mid)

        deleted_by_channel_name: dict[str, int] = {}

        for channel_id, ids in by_channel_bulk.items():
            channel = guild.get_channel(channel_id)
            if channel is None:
                continue
            for i in range(0, len(ids), 100):
                chunk = ids[i : i + 100]
                try:
                    await channel.delete_messages(
                        [discord.Object(id=mid) for mid in chunk]
                    )
                    deleted_by_channel_name[channel.name] = (
                        deleted_by_channel_name.get(channel.name, 0) + len(chunk)
                    )
                except discord.HTTPException:
                    logger.warning(
                        "Purge bulk fallita per il canale %s (Spam Trap).", channel_id
                    )

        for mid in individual_ids:
            channel_id = message_channel.get(mid)
            if channel_id is None:
                continue
            channel = guild.get_channel(channel_id)
            if channel is None:
                continue
            try:
                msg = await channel.fetch_message(mid)
                await msg.delete()
                deleted_by_channel_name[channel.name] = (
                    deleted_by_channel_name.get(channel.name, 0) + 1
                )
            except (discord.NotFound, discord.HTTPException):
                pass

        await spam_trap_repo.delete_indexed_messages(bulk_ids + individual_ids)
        return deleted_by_channel_name

    async def _cleanup_user_artifacts(
        self, guild: discord.Guild, user: discord.abc.User
    ) -> None:
        try:
            async for entry in guild.audit_logs(
                action=discord.AuditLogAction.webhook_create, user=user, limit=20
            ):
                if isinstance(entry.target, discord.Webhook):
                    try:
                        await entry.target.delete(reason="Cleanup after spam trap ban")
                    except discord.HTTPException:
                        pass
        except discord.Forbidden:
            logger.warning(
                "Permessi insufficienti per leggere l'audit log (webhook) nel "
                "server %s.",
                guild.id,
            )

        try:
            async for entry in guild.audit_logs(
                action=discord.AuditLogAction.invite_create, user=user, limit=20
            ):
                if isinstance(entry.target, discord.Invite):
                    try:
                        await entry.target.delete(reason="Cleanup after spam trap ban")
                    except discord.HTTPException:
                        pass
        except discord.Forbidden:
            logger.warning(
                "Permessi insufficienti per leggere l'audit log (inviti) nel "
                "server %s.",
                guild.id,
            )

    async def _send_ban_log(
        self,
        guild: discord.Guild,
        user: discord.abc.User,
        case_number: int,
        trigger_content: str,
        invite_code: str | None,
        invite_creator_id: int | None,
        deleted_by_channel: dict[str, int],
        dm_sent: bool,
    ) -> None:
        config = await spam_trap_repo.get_config(guild.id)
        if config.log_channel_id is None:
            return
        log_channel = guild.get_channel(config.log_channel_id)
        if not isinstance(log_channel, discord.TextChannel):
            return

        embed = discord.Embed(title="🚨 Spam Trap Triggered", color=discord.Color.red())
        embed.add_field(name="User", value=f"{user.mention} ({user.id})", inline=False)
        embed.add_field(
            name="Account created",
            value=discord.utils.format_dt(user.created_at, style="F"),
            inline=True,
        )
        member = guild.get_member(user.id)
        if member is not None and member.joined_at is not None:
            embed.add_field(
                name="Joined",
                value=discord.utils.format_dt(member.joined_at, style="F"),
                inline=True,
            )
        embed.add_field(name="Case", value=f"#{case_number}", inline=True)

        if invite_code is not None:
            creator_mention = f"<@{invite_creator_id}>" if invite_creator_id else "unknown"
            embed.add_field(
                name="Invite used", value=f"`{invite_code}` (by {creator_mention})", inline=False
            )
        else:
            embed.add_field(name="Invite used", value="Could not be determined", inline=False)

        embed.add_field(
            name="Trigger content",
            value=trigger_content[:1000] if trigger_content else "(empty or unavailable)",
            inline=False,
        )

        if deleted_by_channel:
            testo_canali = "\n".join(
                f"#{nome}: {count}" for nome, count in deleted_by_channel.items()
            )
        else:
            testo_canali = "None (covered by native ban cleanup, or nothing to delete)"
        embed.add_field(name="Deleted messages (7-30 days)", value=testo_canali, inline=False)

        embed.add_field(
            name="DM notification", value="Sent" if dm_sent else "Failed (DMs closed)", inline=True
        )

        await log_channel.send(embed=embed)

    # ================================================================
    # Ban appeal
    # ================================================================
    async def _handle_possible_appeal(self, message: discord.Message) -> None:
        user = message.author

        candidati: list[tuple[discord.Guild, object]] = []
        for guild in self.bot.guilds:
            case = await moderation_repo.get_latest_active_case(
                guild.id, user.id, BAN_ACTION_TYPE
            )
            if case is not None:
                candidati.append((guild, case))

        if not candidati:
            return  # non è un DM legato a un ban dello Spam Trap: ignorato silenziosamente

        if len(candidati) > 1:
            corrispondenti = [
                gc for gc in candidati if gc[0].name.lower() in (message.content or "").lower()
            ]
            if len(corrispondenti) == 1:
                candidati = corrispondenti
            else:
                nomi = ", ".join(g.name for g, _ in candidati)
                await message.channel.send(
                    f"You have active bans on multiple servers I moderate: {nomi}. "
                    f"Please mention the server name in your message to continue your appeal."
                )
                return

        guild, case = candidati[0]

        last_appeal = await spam_trap_repo.get_last_appeal(guild.id, user.id)
        if not can_appeal(last_appeal):
            await message.channel.send(
                "You can only submit one appeal every 24 hours. Please wait before trying again."
            )
            return

        await spam_trap_repo.set_last_appeal(guild.id, user.id, datetime.now(timezone.utc))

        config = await spam_trap_repo.get_config(guild.id)
        log_channel = guild.get_channel(config.log_channel_id) if config.log_channel_id else None
        if not isinstance(log_channel, discord.TextChannel):
            await message.channel.send(
                "I couldn't reach the staff of that server. Please try again later."
            )
            return

        incident = await spam_trap_repo.get_incident_by_case(guild.id, case.case_number)

        try:
            thread = await log_channel.create_thread(
                name=f"appeal-case-{case.case_number}",
                type=discord.ChannelType.private_thread,
                reason=f"Ban appeal from {user}",
            )
        except discord.HTTPException:
            await message.channel.send(
                "I couldn't open an appeal thread right now. Please try again later."
            )
            return

        appeal_embed = discord.Embed(
            title=f"Ban Appeal — Case #{case.case_number}",
            description=f"**User:** {user.mention} ({user.id})\n\n"
            f"**Appeal message:**\n{message.content or '(no text)'}",
            color=discord.Color.gold(),
        )
        view = AppealActionsView(guild.id, case.case_number, user.id)

        files = []
        if incident is not None and incident.transcript_html:
            transcript_file = discord.File(
                io.BytesIO(incident.transcript_html.encode("utf-8")),
                filename=f"transcript-case-{case.case_number}.html",
            )
            files.append(transcript_file)

        await thread.send(embed=appeal_embed, view=view, files=files)

        await message.channel.send(
            "Your appeal has been submitted to the staff. They will review it "
            "and may respond here."
        )


async def setup(bot: commands.Bot) -> None:
    registry.register(
        PremiumModule(
            name=MODULE_SPAM_TRAP,
            display_name="Spam Trap",
            description="Canale trappola con ban istantaneo, purge e appeal.",
            premium_capable=True,
        )
    )
    await bot.add_cog(SpamTrapCog(bot))
